-- add FK to ACCOUNTLIST

CREATE TABLE ACCOUNTLIST_NEW(
ACCOUNTID integer primary key
, ACCOUNTNAME TEXT COLLATE NOCASE NOT NULL UNIQUE
, ACCOUNTTYPE TEXT NOT NULL /* Checking, Term, Investment, Credit Card */
, ACCOUNTNUM TEXT
, STATUS TEXT NOT NULL /* Open, Closed */
, NOTES TEXT
, HELDAT TEXT
, WEBSITE TEXT
, CONTACTINFO TEXT
, ACCESSINFO TEXT
, INITIALBAL numeric
, FAVORITEACCT TEXT NOT NULL
, CURRENCYID integer NOT NULL REFERENCES CURRENCYFORMATS
, STATEMENTLOCKED integer
, STATEMENTDATE TEXT
, MINIMUMBALANCE numeric
, CREDITLIMIT numeric
, INTERESTRATE numeric
, PAYMENTDUEDATE text
, MINIMUMPAYMENT numeric
);

INSERT INTO ACCOUNTLIST_NEW SELECT
ACCOUNTID
, ACCOUNTNAME
, ACCOUNTTYPE
, ACCOUNTNUM
, STATUS
, NOTES
, HELDAT
, WEBSITE
, CONTACTINFO
, ACCESSINFO
, INITIALBAL
, FAVORITEACCT
, CURRENCYID
, STATEMENTLOCKED
, STATEMENTDATE
, MINIMUMBALANCE
, CREDITLIMIT
, INTERESTRATE
, PAYMENTDUEDATE
, MINIMUMPAYMENT
FROM ACCOUNTLIST;

DROP INDEX IDX_ACCOUNTLIST_ACCOUNTTYPE;
DROP TABLE ACCOUNTLIST;
ALTER TABLE ACCOUNTLIST_NEW RENAME TO ACCOUNTLIST;
CREATE INDEX IDX_ACCOUNTLIST_ACCOUNTTYPE ON ACCOUNTLIST(ACCOUNTTYPE);

-- add FK to BILLSDEPOSITS

CREATE TABLE ACCOUNTLIST_NEW(
ACCOUNTID integer primary key
, ACCOUNTNAME TEXT COLLATE NOCASE NOT NULL UNIQUE
, ACCOUNTTYPE TEXT NOT NULL /* Checking, Term, Investment, Credit Card */
, ACCOUNTNUM TEXT
, STATUS TEXT NOT NULL /* Open, Closed */
, NOTES TEXT
, HELDAT TEXT
, WEBSITE TEXT
, CONTACTINFO TEXT
, ACCESSINFO TEXT
, INITIALBAL numeric
, FAVORITEACCT TEXT NOT NULL
, CURRENCYID integer NOT NULL REFERENCES CURRENCYFORMATS
, STATEMENTLOCKED integer
, STATEMENTDATE TEXT
, MINIMUMBALANCE numeric
, CREDITLIMIT numeric
, INTERESTRATE numeric
, PAYMENTDUEDATE text
, MINIMUMPAYMENT numeric
);

INSERT INTO ACCOUNTLIST_NEW SELECT
ACCOUNTID
, ACCOUNTNAME
, ACCOUNTTYPE
, ACCOUNTNUM
, STATUS
, NOTES
, HELDAT
, WEBSITE
, CONTACTINFO
, ACCESSINFO
, INITIALBAL
, FAVORITEACCT
, CURRENCYID
, STATEMENTLOCKED
, STATEMENTDATE
, MINIMUMBALANCE
, CREDITLIMIT
, INTERESTRATE
, PAYMENTDUEDATE
, MINIMUMPAYMENT
FROM ACCOUNTLIST;

DROP INDEX IDX_ACCOUNTLIST_ACCOUNTTYPE;
DROP TABLE ACCOUNTLIST;
ALTER TABLE ACCOUNTLIST_NEW RENAME TO ACCOUNTLIST;
CREATE INDEX IDX_ACCOUNTLIST_ACCOUNTTYPE ON ACCOUNTLIST(ACCOUNTTYPE);

-- finish
PRAGMA foreign_keys=ON;
PRAGMA user_version = 20;