PRAGMA foreign_keys=OFF;

-- add FK to ACCOUNTLIST

CREATE TABLE ACCOUNTLIST_NEW(
ACCOUNTID integer primary key
, ACCOUNTNAME TEXT COLLATE NOCASE NOT NULL UNIQUE
, ACCOUNTTYPE TEXT NOT NULL /* Checking, Term, Investment, Credit Card */
, ACCOUNTNUM TEXT
, STATUS TEXT NOT NULL /* Open, Closed */
, NOTES TEXT
, HELDAT TEXT
, WEBSITE TEXT
, CONTACTINFO TEXT
, ACCESSINFO TEXT
, INITIALBAL numeric
, FAVORITEACCT TEXT NOT NULL
, CURRENCYID integer NOT NULL REFERENCES CURRENCYFORMATS
, STATEMENTLOCKED integer
, STATEMENTDATE TEXT
, MINIMUMBALANCE numeric
, CREDITLIMIT numeric
, INTERESTRATE numeric
, PAYMENTDUEDATE text
, MINIMUMPAYMENT numeric
);

INSERT INTO ACCOUNTLIST_NEW SELECT
ACCOUNTID
, ACCOUNTNAME
, ACCOUNTTYPE
, ACCOUNTNUM
, STATUS
, NOTES
, HELDAT
, WEBSITE
, CONTACTINFO
, ACCESSINFO
, INITIALBAL
, FAVORITEACCT
, CURRENCYID
, STATEMENTLOCKED
, STATEMENTDATE
, MINIMUMBALANCE
, CREDITLIMIT
, INTERESTRATE
, PAYMENTDUEDATE
, MINIMUMPAYMENT
FROM ACCOUNTLIST;

DROP INDEX IDX_ACCOUNTLIST_ACCOUNTTYPE;
DROP TABLE ACCOUNTLIST;
ALTER TABLE ACCOUNTLIST_NEW RENAME TO ACCOUNTLIST;
CREATE INDEX IDX_ACCOUNTLIST_ACCOUNTTYPE ON ACCOUNTLIST(ACCOUNTTYPE);

-- add FK to BILLSDEPOSITS

CREATE TABLE BILLSDEPOSITS_NEW(
BDID integer primary key
, ACCOUNTID integer NOT NULL REFERENCES ACCOUNTLIST
, TOACCOUNTID integer REFERENCES ACCOUNTLIST
, PAYEEID integer NOT NULL REFERENCES PAYEE
, TRANSCODE TEXT NOT NULL /* Withdrawal, Deposit, Transfer */
, TRANSAMOUNT numeric NOT NULL
, STATUS TEXT /* None, Reconciled, Void, Follow up, Duplicate */
, TRANSACTIONNUMBER TEXT
, NOTES TEXT
, CATEGID integer REFERENCES CATEGORY
, SUBCATEGID integer REFERENCES SUBCATEGORY
, TRANSDATE TEXT
, FOLLOWUPID integer
, TOTRANSAMOUNT numeric
, REPEATS integer
, NEXTOCCURRENCEDATE TEXT
, NUMOCCURRENCES integer
);

INSERT INTO BILLSDEPOSITS_NEW SELECT
BDID
, ACCOUNTID
, TOACCOUNTID
, PAYEEID
, TRANSCODE
, TRANSAMOUNT
, STATUS
, TRANSACTIONNUMBER
, NOTES
, CATEGID
, SUBCATEGID
, TRANSDATE
, FOLLOWUPID
, TOTRANSAMOUNT
, REPEATS
, NEXTOCCURRENCEDATE
, NUMOCCURRENCES
FROM BILLSDEPOSITS;

DROP INDEX IDX_BILLSDEPOSITS_ACCOUNT;
DROP TABLE BILLSDEPOSITS;
ALTER TABLE BILLSDEPOSITS_NEW RENAME TO BILLSDEPOSITS;
CREATE INDEX IDX_BILLSDEPOSITS_ACCOUNT ON BILLSDEPOSITS (ACCOUNTID, TOACCOUNTID);

-- add FK to BUDGETSPLITTRANSACTIONS

CREATE TABLE BUDGETSPLITTRANSACTIONS_NEW(
SPLITTRANSID integer primary key
, TRANSID integer NOT NULL REFERENCES BILLSDEPOSITS
, CATEGID integer REFERENCES CATEGORY
, SUBCATEGID integer REFERENCES SUBCATEGORY
, SPLITTRANSAMOUNT numeric
);

INSERT INTO BUDGETSPLITTRANSACTIONS_NEW SELECT
SPLITTRANSID
, TRANSID
, CATEGID
, SUBCATEGID
, SPLITTRANSAMOUNT
FROM BUDGETSPLITTRANSACTIONS;

DROP INDEX IDX_BUDGETSPLITTRANSACTIONS_TRANSID;
DROP TABLE BUDGETSPLITTRANSACTIONS;
ALTER TABLE BUDGETSPLITTRANSACTIONS_NEW RENAME TO BUDGETSPLITTRANSACTIONS;
CREATE INDEX IDX_BUDGETSPLITTRANSACTIONS_TRANSID ON BUDGETSPLITTRANSACTIONS(TRANSID);

-- finish
PRAGMA foreign_keys=ON;
PRAGMA user_version = 20;